.travis.yml
platformio.ini

* This board is meaningful because it is cheap, comes with a
built-in OLED display *AND* has a built-in LoRa radio enabling
over 6 Miles (10km) of long-range communication at a slow rate.
* Firmware boots, produces serial output, and blinks the Wifi LED
on my local hardware.

platform: Add Heltec ESP32 board

---

platformio.ini
src/app_config.cpp
src/app_config.h
src/main.cpp
src/tesla_client.cpp
src/tesla_client.h
src/web_server.cpp

needs latest ArduinoMongoose from https://github.com/jeremypoulter/ArduinoMongoose

Tesla API support

---

divert_sim/RapiSender.cpp
divert_sim/divert_sim.cpp
src/app_config.cpp
src/app_config.h
src/divert.cpp

Adds a divert_PV_ratio parameter with a default value of 1.0 that 
requires 100% of PV power for starting charging. There is a related wifi gui
pull request. This compiles fines but has not been tested. Some feedback
from the Open EVSE team would be welcome before I test flashing my
ESP32.
Motivation
Because charge cannot start with less than 6A, and is incremented by
steps of 1A, it is not possible for OpenEVSE to exactly consume the
available excess of PV power. The divert_PV_ratio declares what
minimum fraction of PV power is required to start charging or
increment charging current.
The default of 1.0 means that charging only starts (or is incremented)
when all the required power is available as excess PV power. A higher
value (1.1) would start only with an extra safety margin.
Values …

divert_PV_ratio: adjustable requirement on available PV power before starting charge or incrementing current

---

platformio.ini
src/input.cpp
src/input.h
src/web_server.cpp

This flag was first introduced in 2017, and now that we've moved from
ESP8266 to ESP32, this feels like a good time to get rid of this code.
It is not enabled by default in any build configuration, and a lot of it
was gutted in an earlier commit 48cc8e064.
This endpoint has been merged with the status endpoint since 2017 in
commit 54987e6bdaa.
@jeremypoulter, I would definitely appreciate your input here on whether this is a good idea, and if not, why this should stick around as I'm not sure what would still be expecting to use this.

Remove the legacy API and ENABLE_LEGACY_API flag

---

src/ota.cpp
src/web_server_static.cpp

Two minor fixes:
- Fix CORS for zones.js, by adding "Access-Control-Allow-Origin" header to all static requests
- timeout using espota for upload, by add feedLoopWDT in onProgress

Fix CORS for zones.js and timeout using espota for upload

---

src/web_server.cpp

Using via openevse.local gave CORS errors when posting to /config. (Due to preflight OPTIONS request not being handled properly: [Mozilla Documentation](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request#:~:text=A%20CORS%20preflight%20request%20is,Headers%20%2C%20and%20the%20Origin%20header).)

CORS fix for /config

---

src/mqtt.cpp

Voltage is used by divert mode, as well as sent along to the OpenEVSE
module for power calculations.
Setting this to zero could result in a lot of issues. The divert code
would see divide by zero happen, and the energy montoring code on the
OpenEVSE module would result in the recorded energy usage being
incorrect.
While this shouldn't happen reguarly, I found myself in this situation
by sending a null/zero-length message to the relevant topic that the
ESP32 was listening on. Because there is no error checking in the float
parsing code, a null value parsed to zero, which resulted in the voltage
value being set to zero.
An alternative here would be to reset the voltage to `DEFAULT_VOLTAGE`
if a zero or invalid value was received. As written, this will simply do
nothing and ignore the …

Don't allow voltage to be set outside of 60-300 volts via MQTT

---

platformio.ini

Prevents lockup should EVSE Monitor be started twice. We possibly should look at why this is happening, but I think it is 'ok' as there are a few paths that could cause the the RAPI to detect the EVSE as booted so fixed MicroTasks to prevent multiple starts.
FIxes #169

Bump to latest MicroTasks

---

src/emonesp.h
src/net_manager.cpp

Fixes Failure to connect to AP when poor signal #205. Based on findings by @julianwb in #206.

Reset the WiFi state after receiving a disconnect event

---

src/input.cpp
src/time_man.cpp

On making a connection to the EVSE we read the time as the EVSE module may have a battery backed RTC or even just it has remained on during reboot.
However it also may not have a useful time set, eg when recovering from a power cut and no battery backed RTC. In ths case there is a race condition between getting the time from NTP and the time from the EVSE. So now we only set to the EVSE time if it is later than the local ESP time.
This fixes NTP not automatically working  #194.

Only update to the EVSE time if later than the ESP32 time.

---

.github/dependabot.yml
.github/workflows/build.yaml

Extended workflow to create/update a pre-release called latest after each commit/merge to master, uploading the generated assets to that release. The binaries can then be downloaded and tested and the release promoted to a full release if as needed.
Fixes #262

Automated Release process

---

src/lcd.cpp
src/lcd.h

The Session and Lifetime values will now automatically scale as the number increases from Wh->kWh->mWh and so on.
Also right justify the the values to look a bit nearer .
Fixes Display session energy as kW with one decimal place #264

Updated to scale the energy values

---

platformio.ini

`LED_BUILTIN` was not set to `0` so was pulling the button low and getting stuck in a reset loop.
Fixes #254

Corrected the LED setting for NodeMCU boards

---

src/lcd.cpp
src/net_manager.cpp

When there are multiple messages to display immediately the we where missing the null check on the loop.
Fixes #251

Fixed crash when enabling the access point/factory resetting via the button

---

src/lcd.cpp

When displaying the timer start/stop times the Start/Stop was being included in the `value` parameter of `displayNameValue` so it was getting repeated. This change removes that duplication, fixes #305

Fixes for extra chars when displaying the timer start/stop times

---

docs/user-guide.md

I just went through recovery on a Huzzah board through serial flash (I uploaded the wrong image - PEBKAC) and after a lot of frustration and reading online, figured out the exact button sequence to trigger a download.  This adds that to the flash notes.

Huzzah board button press note

---

docs/developer-guide.md
docs/wired-ethernet.md
platformio.ini
src/net_manager.cpp

This leaves a bit to be desired on the ethernet docs, but I think is a step in the right direction there.  Aim is to be sufficient to put the ESP32-PoE-ISO board at the same standard as ESP32-GATEWAY.

ESP32-PoE-ISO support, Ethernet doc reorg

---

src/lcd.cpp

The metric units fix here should be uncontroversial- we need to be using `MWh`, not `mWh`, to be megawatt-hours, not milliwatt-hours. https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes
The date one might be a bit less desired, but I'd advocate for making the change. The OpenEVSE web UI has the advantage of being able to use the browser/OS date format, but the LCD display format is hardcoded. By using the ISO date format, there should be no confusion with a date such as "04/07/2022" - is this April 7th (as a US resident would likely interpret it), or July 4th (as most of the rest of the world would use)? By displaying "2022-07-04", it is much less ambiguous.

LCD info display corrections and date format tweak

---

src/http_update.cpp

I've only spent a couple minutes testing this on an ESP32-PoE-ISO board, but it seems to work, and it compiles OK for the targets on the releases page.
Fixes #187

Issue #187 - Feed watchdog in http_update_write()

---

platformio.ini
src/app_config.cpp
src/app_config.h
src/app_config_v1.cpp
src/web_server_config.cpp
test/config.http

By adding the header `X-Storage: factory` to the HTTP on the first call the settings will be saved to a different area of flash. This allows for unique IDs and passwords to be set at the factory that will be preserved after a factory reset.

Added the ability to set some write once 'factory' settings

---

src/main.cpp
test/serial_config.txt

Send either `conifig:` or `factory:` followed by required config settings in a JSON block, as per the HTTP `/config` endpoint all terminated by a `\n`, eg:
```
config:{"www_username":"admin","www_password":"admin"}
```

Added ability to set the config (including factory config) over serial

---

src/evse_monitor.cpp
src/input.cpp
src/main.cpp
src/web_server.cpp

discussed here https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/401#issuecomment-1279959862
Add missing events over web socket / mqtt
Send full status data over web socket when new client connect
fix Pilot event bug

Add some events through websocket & mqtt

---

src/scheduler.cpp

This is to ensure that the eco mode does not conflict ad the timer will operate as a boost if used at the same as echo mode.
Fixes #459

Set the charge rate on the schedule

---

src/current_shaper.cpp
src/web_server.cpp

This should fix some priority issues I'had been reported.
There's no need of shaper doing it's job when divert is active in eco mode

prevent shaper to control charge_current if divert mode is active

---

src/http_update.cpp

This send "upload_progress" value to websocket while uploading
It gives better upload file progress bar as it seems to be broken using classic progress event from xmlhttprequest ( also can't work correctly behind proxy ) 
I'm using it on wip UI , demo at the end of video here https://watch.screencastify.com/v/EP73NnuERNFHosoQAR92

add upload_progress event to websocket

---

src/evse_man.cpp
src/evse_man.h
src/manual.cpp
src/mqtt.cpp
src/web_server.cpp

[add auto_release to /override](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/485/commits/793797ed593b8aeef423e327b744838092f087d5)
[fix override publication missed on mqtt](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/485/commits/c3dbf83194365db88b168055b0ab2cfb63c4e184)
[fix mqtt /override topic publishing too much props](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/485/commits/71663dd4c4c7004429c367b8da85ed3884790178)

improvment & fixes of MQTT /override topic

---

src/current_shaper.cpp
src/current_shaper.h
src/mqtt.cpp
src/web_server.cpp

WARNING! If you were manually changing max_current using HTTP API or MQTT, don't forget to switch to charge_current now

Current Shaper now use "max_current" instead of "charge_current".

---

src/mqtt.cpp
src/mqtt.h

little grouped PR:
Event send missing "mqtt_connected" at connection / error ( no disconnect yet, missing disconnection event in mongooseMQTT )
Temporise publishing part of mqtt loop ( each 500ms 
Reduced some MQTT jsonObject size ( claim/override )

Event send missing "mqtt_connected" at connection / error 

---

src/evse_monitor.cpp

do not set Scheduler claim if evse module communication is not ready

---

src/web_server.cpp

On a quick scan there does not look to be a readily avalible library for ASCII to UTF-8 conversion, so as we don't have all that many cases where this is an issue, basically just the space on the LCD, just a quick hack to ensure valid UTF-8 is sent.
Fixes #509

Quick and dirty filter to ensure no >127 chars are sent over the websocket and hense valid UTF-8 is sent

---

src/app_config.cpp
src/app_config.h
src/evse_man.h

Factors _monitor.getAmps() by 3 in _evse.getAmps() if true
This should fix current_shaper & divert mode beeing wrong with threephase, and displays on UI.
fix #472
still needs evse module fw compiled with -D THREEPHASE

Adds is_threephase virtualbool switch.

---

src/current_shaper.cpp
src/current_shaper.h
src/mqtt.cpp
src/web_server.cpp

Now shaper can work while divert is active.
produced energy or grid export is added to shaper max_pwr value
This is mostly necessary when Divert stays at 6amp waiting for smoothed current to get down before shutting down.
If the grid doesn't has enough amp available it can overload. This should prevent it.
and other little commits

Enable Shaper with Divert mode active

---

src/current_shaper.cpp
src/evse_man.h

fix mistake in previous pr
revert wrong calc getAmps()*3 for threephase from previous commit ( we don't sum current/phase but power/phase)

fix current shaper for threephase + amp display 

---

src/evse_monitor.cpp
src/evse_monitor.h

Until the bug is corrected on evse fw, this solves the issue and prevent the charge_current going to max when Evse goes from Disabled to Active state ignoring claims & pilot values
fix #452 and should also fix #513 fix #388 fix #481
Edit: It seems those bugs are related to PP_AUTO_AMPACITY beeing set. Posted an issue there: https://github.com/lincomatic/open_evse/issues/156?fbclid=IwAR37MVzzv2WZ7iDPPr3lkryBSUIvsDBsbPJkFu5PcZG1JgMT7e2LF6KxFzQ
So this is not really an OpenEvse bug, but more that OpenEvse and Wifi module don't share the non tethered chargers checking cable ampacity state and we have confusions here.

fix #452 reevaluate claims if amps > pilot

---

src/lcd.cpp
src/scheduler.cpp

getNextEvent could get stuck in an infinate loop if searching for a type that is not in the list. This can happen when there is only enteries ofa single type, eg disabled and you search for active, as the LCD module does causing a watchdog timeout.
Fixes #414

Fix for infinate loop in getNextEvent

---

platformio.ini
src/evse_monitor.cpp

Unlock Evse module when Wifi module is ready

---

src/current_shaper.cpp
src/divert.cpp
src/mqtt.cpp

Allow shaper to use same topic as grid_ie
fix shaper with grid_ie
should fix divert with threephase enabled

Allow shaper to use same topic as grid_ie

---

platformio.ini
src/http_update.cpp
src/root_ca.cpp
test/update.http

Support for updating directly from GitHub

---

src/web_server.cpp

let wifi module answer to ping over websocket
Handled on UIv2 (pingpong branch ) for proper disconnection/reconnection
( client send a ping if it hasn't received data for 5sec ) , tries 3 times each sec if it doesn't get an answer, then tries to reconnect to server ) . Behavior could be mirrored on UI1 too ( no need to send a ping each sec anymore  )

ping pong over websocket

---

src/energy_meter.cpp
src/input.cpp
src/main.cpp
src/web_server.cpp

forgot this one
Also put the deprecated properties in create_rapi_json as they are missing for emoncms publish
( time to ask emoncms to use the new properties before deprecation )
edit: is there a good reason why data are sent separately to emoncms instead of using event_send like websocket & mqtt?
Also it seems we should send the full /status topic to emoncms instead of create_rapi_json as more data are now coming from ESP32 and not RAPI.

add missing energyMeter data to emoncmss_publish()

---

src/energy_meter.cpp

fix monthly counter wrong
session data initialised at reboot
fix time now using localtime for rotate()
publish energyMeter after counters reset

some EnergyMeter fixes

---

.github/workflows/release_validation.yaml
scripts/auto_fw_version.py
src/main.cpp

Updated the auto version number script to use the correct GitHub environment variables to get the version number when running on GitHub Actions.
Added the `_modified` suffix to the version number when the working directory is not clean. This is to ensure that the version number is always different when the working directory is not clean.
Added the `GIT_HASH` define with the short hash of the current commit. This is to make it easier to identify the exact commit that was used to build the binary.
Fixes #584

Fixes to the auto version number script

---

scripts/auto_fw_version.py

this will output local_branchname_hash, less confusing when developping between branches

add branch name to local build_version

---

docs/mqtt.md
src/divert.cpp
src/input.cpp
src/mqtt.cpp

Using the RAPI MQTT topic to set the max_current_soft ($SC) does not correctly refresh the UI. It's best to expose it. Also, restart of the gateway was missing.

Expose restart and max_current through mqtt

---

src/web_server.cpp

Fix browser console spawning HTTP 404 error when API answer was correct. Was preventing to catch real 404 errors.
@jeremypoulter , do you think we should also change the {msg: "no override"} and co by empty objects {} ?

switch from 404 to 200 response from REST API when there's no error

---

src/lcd.cpp

This fixes issues during firmware update where the incomming data also blocks the CPU and the LCD was not being updated, especcially over Ethernet as the data is received much faster than WiFI.
Fixes #597

Changes to block until the LCD update has completed if the `LCD_DISPLAY_NOW` is set

---

scripts/extra_script.py

platformio doesn't appear to define $BUILDSRC_DIR, which means the
generated dependencies never matched actual files and the GUI would
not be regenerated from modified sources.

Fix GUI update rules when BUILDSRC_DIR is not defined

---

src/ocpp.cpp

'C' is not listed as a UnitOfMeasure in OCPP 1.6 Section 7.45. Changing 'C' to 'Celsius' to appease protocol validators.

Change C to Celsius for OCPP MeterValue

---

.github/workflows/build.yaml
platformio.ini

Added Support for wt32-eth01 board. Need to add a 1uF ceramic capacitor between pins EN and GND to avoid boot problems

Added Support for wt32-eth01 board - Update platformio.ini

---

.github/workflows/build.yaml
platformio.ini

As I tried to foist this off in #713, this adds support for the [ESP32-C3 devkit](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/hw-reference/esp32c3/user-guide-devkitc-02.html) that seems to be working just fine after a month of use. I am using a more recent espressif32 release (6.4.0)  though, as the C3 isn't supported on 6.0.1.
I chose GPIO6 for RAPI TX and GPIO7 for RAPI RX somewhat arbitrarily, just because they aren't ADC pins or the USB DP/DN pins, JTAG pin, or UART0 TX/RX.
| Pin | Function |
|--|--|
| GPIO0 | WiFi Button / BOOT |
| GPIO6 | RAPI TX |
| GPIO7 | RAPI RX |
| GPIO8 | RGB LED |
| GPIO21 | USB Serial TX (cp2102) |
| GPIO20 | USB Serial RX (cp2102) | 
Log messages come out the USB port, the RGB LED color cycles on boot, and my OpenEVSE works just fine with …

Add esp32-c3-devkitc-02

---

src/current_shaper.cpp

Did for current shaper not working under certain circumstances 

---

.github/workflows/dependabot.yml
platformio.ini

Library updates

---

platformio.ini

Add the missing build flags to enable I2C devices (NFC reader and Temperature sensor).

Fix TFT I2C devices

---

src/ocpp.cpp

Fixed spelling errors on NFC card read 'unknown' that have been bothering me while testing OCPP NFC functionality on my project.

Update ocpp.cpp to fix spelling errors on LCD display.

---

src/energy_meter.cpp
src/energy_meter.h
src/evse_man.h

Much of this code was copied from the low-level firmware side, where we don't have floating point available, and had to use some tricks to ensure we didn't lose precision. (I should know- I wrote it!) Since this doesn't apply in our ESP32 code, we can just multiply the three values (volts, amps, milliseconds) together to get milliwatt-seconds.
Additionally, we should store elapsed as a floating point value, not an integer number of seconds. As we're going through the pool loop, which repeats every 1000 ms, we might not hit that value exactly. Imagine we are closer to 1020 ms instead due to the work we need to do each iteration. That would allow our elapsed second counter, which stores a truncated value (1020ms gets rounded to integer 1 second), to drift by 1 second every 50 seconds.

Clean up, simplify, and correct some energy meter code

---

platformio.ini
src/evse_monitor.cpp

There was a check to see if the EVSE was not in the starting state, but it does not exit starting until the boot lock in cleared. Just removed that check as it is not needed as there is a flag to indicate if the boot lock is set.
Fixes #798 “Waiting for initialization” after power loss

Be more agressive about clearing the boot lock

---

.github/workflows/build.yaml

Grab the bootloader and partition files for 4MB and 16MB builds
`marvinpinto/action-automatic-releases` no longer looks to be maintained and for some reason we are using a different actions for the latest and proper release, so used `softprops/action-gh-release` for both cases.

Tweaks to the release workflows

---

platformio.ini
src/LedManagerTask.cpp
src/LedManagerTask.h
src/main.cpp

Here is my modification to the original OpenEVSE project to introduce a led bar as most commercial EVSEs have as seen in this discussion thread https://github.com/OpenEVSE/openevse_esp32_firmware/discussions/891
I'm based on WS2812FX library to perform animations and visual effects.
My first intention is to show visually the status of the EVSE without using the screen nor the web interface and know quickly what is happening in the EVSE as follows:
If the EVSE is not charging the car, the bar have the same color code as the EVSE led (screen, buttons, etc) based on EVSE status
If the EVSE has any error, the led is blinking with corresponding color code
IF the EVSE is loading the car, the led will perform a "loading bar" animation to show this status. Also the speed of the animation will …

Adding LedBar Animation for Visual effects of OpenEVSE activity and status

---

platformio.ini
src/LedManagerTask.cpp

Also adding the fade annimation to the error state. This was mostly a bit of a test as I can't perswade my test board to go into charging mode, but also makes the error state more visiable from the other static colours

Added support for the LED animations on the WiFi LCD board

---

src/app_config.cpp
src/evse_man.h
src/evse_monitor.cpp
src/evse_monitor.h

parts of fix for #928, I've added the gui part for setting scale & offset.
scale & offset are not updating in /config endpoint after changes. Wifi module needed reboot to get new values.
I've made a mistake and [pushed the gui change](https://github.com/OpenEVSE/openevse-gui-v2/commit/66d038941ebdd593e24a52181f8f64db7a66a91a) in main repository instead of mine ( made a long time I haven't worked on this project, forgot I had write access to the git, seems I'm a bit rusty  ) 
@jeremypoulter , If it's a problem can you revert it and I'll make a proper PR for gui too.

Fix scale & offset not updated in config after submitting changes #928

---

docs/mqtt.md

Copied definitions from https://openevse.stoplight.io/docs/openevse-wifi-v4/dba95e8966593-get-the-evse-status  (verified these values make sense experimentally)

Fix divertmode MQTT docs to match HTTP API

---

src/lcd_tft.cpp
src/lcd_tft.h

By popular demand: Uses the big digits to display the measured power during charging.  When not charging, the pilot current setting is displayed here as before.
As there's only room for 3 digits, the number of decimal places changes to fit the available space.

TFT big power display during charging

---

src/evse_man.cpp

In past versions we could use this RAPI commands:
--> $F0 0 and $FB 0 in order to freeze the display a put the background to black (so the leds of the display are turned off)
Also:
--> $F0 1 in order to turn on the display
But sine v5, for security reasons these commands were blocked. This PR is to bring back al least this two commands to recover that feature that is very useful for many users. 
Discussed/asked here: https://github.com/OpenEVSE/openevse_esp32_firmware/issues/725

Enable RAPI commands in order to turn off the display
