OpenEVSE/openevse_esp32_firmware

src/web_server.cpp
Thanks to @MarkNinja a potential fir for #61
=> WiFi Stability fixes

platformio.ini, src/LedManagerTask.cpp, src/LedManagerTask.h, src/emonesp.h, src/input.cpp, src/main.cpp, src/net_manager.cpp, src/web_server.cpp
Initial support for the OpenEVSE WiFi v1 board, #91 and #92
=> OpenEVSE WiFi v1 support

src/divert.cpp
Fixes Log Solar PV divert MQTT data to Emoncms #196
=> Publish Divert values to EmonCMS

platformio.ini
Fixes V4.0  Check for an remove existing RAPI timers & disable RAPI timer set via MQTT/HTTP #170
=> Fix for not clearing timers on startup

platformio.ini
=> Latest OpenEVSE library with LCD space fix

platformio.ini, src/LedManagerTask.cpp, src/LedManagerTask.h
=> Added support for restricting the WiFi status to a single pixel

platformio.ini, src/app_config.cpp, src/evse_monitor.cpp, src/web_server_config.cpp, test/claims.http
=> Properly handle setting the max current by setting in the value in the EVSE EEPROM rather than the WiFi config

src/app_config.cpp, src/mqtt.cpp
missing yield() after some mqtt subscription
=> remove mqtt_retained declaration, conflict with virtualbool

src/current_shaper.cpp, src/web_server.cpp
Update voltage, shaper_live_pwr, solar, grid_ie, battery_level, battery_range, time_to_full_charge by HTTP with POST /states 
Fix https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/439
=> fix #439  added POST /states

.github/workflows/build.yaml, platformio.ini
also
- added a dev version of the rev F build
- added some missing builds to the GitHub build
=> Small tidy-up of the ESP32 gateway configs

src/current_shaper.cpp, src/evse_man.cpp, src/manual.cpp, src/manual.h, src/mqtt.cpp, src/web_server.cpp
added override version
fix shaper not realeasing claim when Divert is active
moved mqtt_publish_claims() call from evse_man to mqtt.h loop
change claims version to always increment
=> override version +  fixes

src/web_server.cpp, src/web_server_config.cpp
=> fix  #496 #492 increased json object size

src/time_man.cpp
=> No longer endlessly loop twhen switching from NTP -> Manual time

platformio.ini, src/LedManagerTask.cpp, src/LedManagerTask.h
As a consiquance removed the analogueWrite (not compatible) lib and moved over to the built in ledc.
Also fixed #352 LED Brightness slider bug.
=> Update to the latest ESP32 core

.github/workflows/build.yaml
change dev builds file names to use same patterns together &  be consistant with release file names ( i.e openevse_wifi_v1_dev_gui-v1|v2  )
=> change dev builds file names

src/net_manager.cpp
=> change default "CN" country code to "world safe mode" ("01")

src/evse_man.cpp, src/evse_man.h
=> Removed _waitingForEvent as Wifi module control everything nows.

src/energy_meter.cpp, src/evse_monitor.cpp
( was not rotating data correctly )
probably fix #594
=> loop energyMeter.update() even when not charging

src/time_man.cpp
time was lagging behind after ntp update. 
perhaps fix #621
=> fix time not updated immediately after NTP change

divert_sim/Makefile, divert_sim/divert_sim.cpp
Needed for the new InputFilter in #590
=> Changes to update millis based on the time simulated time

.github/workflows/build.yaml, .github/workflows/divert_sim.yaml, divert_sim/test_divert.py
and a few other workflow tweeks
=> Separate test/function per dataset so the rest report is a bit more verbose

.github/workflows/build.yaml, docs/developer-guide.md, docs/process.md, docs/wired-ethernet.md, models/Config.yaml, platformio.ini, prepare-release.sh, test/basic.http, test/update.http
=> More accurate build names

docs/developer-guide.md
Fix a couple of links in developer guide
=> docs: fix custom python build script and GUI v2 links

src/ocpp.cpp
Recent OCPP merge undid typo fix. Re-fixing.
=> Fix regression after recent merge

src/lcd.cpp, src/lcd_tft.cpp, src/lcd_tft.h
=> Display the 'old' LCD message in place of the host/time

platformio.ini
=> Use latest (6.x) version of the ArduinoMongoose to resolver issues with Safari
